# Generated by Django 2.1.2 on 2018-10-15 17:57

from django.db import migrations, models

def default_projects(apps, schema_editor):

    names = ['Proyecto 1', 'Proyecto 2']

    Project = apps.get_model("psatimetracker", "Project")
    for project in names:
        p = Project(name = project)
        p.save()

def delete_projects(apps, schema_editor):
    Project = apps.get_model("psatimetracker", "Project")
    Project.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('psatimetracker', '0002_auto_20181015_1939'),
    ]

    operations = [
        migrations.RunPython(default_projects, delete_projects),
    ]