# Generated by Django 2.1.2 on 2018-10-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psatimetracker', '0004_auto_20181015_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkedHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField()),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='completedTime',
        ),
        migrations.AddField(
            model_name='workedhours',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psatimetracker.Task'),
        ),
    ]
