# Generated by Django 2.1.2 on 2018-10-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatimetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='developer',
        ),
        migrations.AddField(
            model_name='task',
            name='developers',
            field=models.ManyToManyField(to='psatimetracker.Developer'),
        ),
    ]
